add pgadmin to docker compose
stac-utils/stac-fastapi pull request #551
Opened 2023-03-29 10:18 UTC by romeokienzler

**Related Issue(s):**

- #550 

**Description:**
Add pgadmin to docker-compose (UX/DX improvement)
**PR Checklist:**

- [ ] `pre-commit` hooks pass locally
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md).

2023-03-30 13:36 UTC, gadomski reviewed
I could be convinced otherwise, but my initial instinct is that this is out-of-scope for this repository. Users can always set up their own **pgadmin** instance against their **pgstac**, and I'm not sure we need to provide that for them.

If this is useful information, could it be provided via documentation instead of another infrastructure file? I'm just trying to reduce the number of things we need to keep up-to-date and tested in this repo.

If we do want to keep this new docker-compose file, we should probably add a CI step to spin it up and run a smoke test, just to make sure it's still valid.

2023-03-30 13:36 UTC, gadomski commented on docker/servers.json
What's this file for? Is this required for pgadmin support?

2023-03-31 22:53 UTC, romeokienzler commented on docker/servers.json
yes - this is the config file pgadmin reads containing the DB connection details

2023-03-31 22:57 UTC, romeokienzler commented
> Users can always set up their own pgadmin instance against their pgstac

Not trying to convince anybody here, I just needed it and wanted to share my work with others. If you want to contribute to this project (which I'm planning to) it is useful to have pgadmin handy - and running it on docker alongside with the rest involves some complex networking which I've taken care of.

So I let you decide - if you wanna have it as a 3rd option, I'm happy to include it in automated testing, if not we can close this PR

Either way is fine for me

2023-04-03 13:09 UTC, gadomski requested changes

2023-04-03 13:09 UTC, gadomski commented on docker/servers.json
> +            "Host": "pgstac,
```suggestion
            "Host": "pgstac",
```

2023-04-03 13:47 UTC, rajadain commented
My 2 cents: I agree with @gadomski, don't think the inclusion of pgAdmin is a natural fit here. I personally use TablePlus and Postico, I'm sure there's other alternatives out there. Because pgAdmin isn't fundamental to the purpose of this library, don't think it should be included (single purpose principle).

The guidance provided in this PR on how to connect such a Postgres client to the database is useful though. Perhaps this could go in a FAQ / Guides section of the documentation?

2023-04-10 11:50 UTC, gadomski commented
@romeokienzler so I think the best course of action would be to add these instructions to the documentation, rather than as infrastructure code. Would you like to do that in this PR, or should I close this and you can open a docs PR later if you'd like?

2023-04-13 09:14 UTC, romeokienzler commented
Hi @gadomski let me use this PR, will ping when ready...thanks a lot!

2023-04-13 09:50 UTC, romeokienzler commented
@gadomski @rajadain please have a look

2023-04-13 11:33 UTC, gadomski requested changes

2023-04-13 11:33 UTC, gadomski commented on README.md
> +```
Thanks! I think the text looks good ... but feels a little specific for the `README.md`. Can you add it to the `tips-and-tricks` page in the documentation? https://github.com/stac-utils/stac-fastapi/blob/main/docs/tips-and-tricks.md

2023-04-13 11:33 UTC, gadomski commented on docker/servers.json
File shouldn't be removed since we're not providing any infrastructure, just documentation.

2024-04-10 08:00 UTC, jonhealy1 commented
@gadomski @vincentsarago @romeokienzler This is really valuable. I would use this but I think it should be moved to the stac-fastapi-pgstac repository now as this repo is database-agnostic.

2024-04-10 08:06 UTC, vincentsarago commented
@jonhealy1 yeah it makes sense

2024-04-10 16:38 UTC, closed without merging