Adding Collection Search Extension
stac-utils/stac-fastapi pull request #681
Opened 2024-05-03 12:42 UTC by tjellicoe-tpzuk

**Related Issue(s):** N/A

**Description:** Adding Collection Search Extension as defined [here](https://github.com/stac-api-extensions/collection-search)

**PR Checklist:**

- [ ] `pre-commit` hooks pass locally
- [ ] Tests pass (run `make test`)
- [ ] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md).

2024-05-14 09:29 UTC, vincentsarago commented on stac_fastapi/extensions/stac_fastapi/extensions/core/collectionSearch/collectionSearch.py
> +        POST /collection-search
we should add a note that the extension seems to mention `GET /collections` and `POST /collections` but due to possible conflict with the `transaction` extension we should to use `/collection-search`

also wonder if we should use `/collections-search` or `/search/collections` 🤷‍♂️

2024-05-15 11:00 UTC, vincentsarago commented on stac_fastapi/api/stac_fastapi/api/app.py
> +            path="/catalogs/{catalog_id}collections/{collection_id}/items/{item_id}",
😬 maybe this change wasn't made on purpose?

2024-05-17 10:44 UTC, m-mohr requested changes
This doesn't implement https://github.com/stac-api-extensions/collection-search

The extension doesn't define a POST /collections endpoint, only GET /collections. The endpoint names are wrong.

> All functionality in OGC API - Records - Part 1: Local Resource Catalogue is only defined for the GET method (i.e. GET /collections). Note: STAC may add behavior for POST /collections in the future, but due to a potential conflict with the Transaction Extension, specific rules for content negotiation might be required.

2024-05-17 10:52 UTC, tjellicoe-tpzuk commented
Thanks for your comments @vincentsarago and @m-mohr, this PR has become mixed up with subsequent commits, I will raise a new one only containing the updates for the collection search extension - see  draft PR #693

2024-05-17 10:52 UTC, closed without merging